console.log('Church Volunteer Scheduler v1.0.0-alpha3 professional UI');
import { auth, db, firebaseConfigured } from './firebase.js';
import {
  createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut,
  sendPasswordResetEmail, onAuthStateChanged, updatePassword
} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import {
  collection, doc, getDoc, setDoc, updateDoc, deleteDoc, addDoc,
  onSnapshot, serverTimestamp, query, orderBy, where, getDocs
} from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const $ = s => document.querySelector(s);
const appEl = $('#app');
const nowDate = () => new Date().toISOString().slice(0,10);
const esc = (s='') => String(s ?? '').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fmtDate = d => d ? new Date(d+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'}) : '';
const timeLabel = t => { if(!t)return ''; let [h,m]=String(t).split(':').map(Number); const a=h>=12?'PM':'AM'; h=h%12||12; return `${h}:${String(m||0).padStart(2,'0')} ${a}`; };

let state={user:null,profile:null,services:[],ministries:[],roles:[],users:[],assignments:[],ready:false,view:localStorage.getItem('cvsView')||'home',calendarMonth:nowDate().slice(0,7),selectedCalendarDate:nowDate()};
let unsubs=[];
const cleanup=()=>{unsubs.forEach(fn=>fn&&fn());unsubs=[]};
const isAdmin=()=>state.profile?.role==='admin';
const isCoordinator=()=>['coordinator','admin'].includes(state.profile?.role);
const isVolunteer=()=>state.profile?.role==='volunteer';
const canManageService=()=>isCoordinator();

function friendly(e){const m={'auth/email-already-in-use':'This email is already registered.','auth/weak-password':'Password must be at least 6 characters.','auth/invalid-email':'Please enter a valid email.','auth/invalid-credential':'Email or password is incorrect.','auth/network-request-failed':'Please check your internet connection.','permission-denied':'You do not have permission for that action.'};return m[e?.code]||e?.message||'Something went wrong.'}

if(!firebaseConfigured){renderSetup();} else onAuthStateChanged(auth,async user=>{cleanup();state={...state,user,profile:null,services:[],ministries:[],roles:[],users:[],assignments:[],ready:false};if(!user)return renderLogin();await ensureProfile(user);startListeners();});

function renderSetup(){appEl.innerHTML=`<div class="wrap login"><div><div class="hero brandHero loginBrandHero"><div class="brandLeft"><img src="images/church-logo.svg" class="powerDinkLogo" alt="Church logo"><span class="brandDivider"></span><div class="brandTitle"><h1>Church Volunteer Scheduler</h1><p>v1.0.0 Alpha 3</p></div></div></div><div class="card"><h2>Connect Firebase First</h2><div class="notice warn"><b>This build is ready, but it is intentionally not connected to the old Pickleball database.</b></div><p>Open <code>js/firebase.js</code> and paste the Web App configuration from your new church Firebase project.</p><p class="small">This protects your existing PowerDink data from being mixed with church schedules.</p></div></div></div>`}

async function ensureProfile(user){const ref=doc(db,'users',user.uid);let snap=await getDoc(ref);if(!snap.exists()){await setDoc(ref,{name:user.email.split('@')[0],email:user.email,status:'pending',role:'pending',ministryIds:[],createdAt:serverTimestamp()});snap=await getDoc(ref)}state.profile={id:user.uid,...snap.data()}}
function startListeners(){
  unsubs.push(onSnapshot(query(collection(db,'services'),orderBy('date')),s=>{state.services=s.docs.map(d=>({id:d.id,...d.data()}));state.ready=true;render()},renderError));
  unsubs.push(onSnapshot(collection(db,'ministries'),s=>{state.ministries=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0));render()},console.error));
  unsubs.push(onSnapshot(collection(db,'roles'),s=>{state.roles=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.sortOrder||0)-(b.sortOrder||0));render()},console.error));
  unsubs.push(onSnapshot(collection(db,'assignments'),s=>{state.assignments=s.docs.map(d=>({id:d.id,...d.data()}));render()},console.error));
  unsubs.push(onSnapshot(doc(db,'users',state.user.uid),s=>{if(s.exists()){state.profile={id:s.id,...s.data()};render()}},console.error));
  if(isAdmin())unsubs.push(onSnapshot(collection(db,'users'),s=>{state.users=s.docs.map(d=>({id:d.id,...d.data()}));render()},console.error));
}
function renderError(e){appEl.innerHTML=`<div class="wrap"><div class="card"><h2>Firebase Error</h2><div class="error">${esc(friendly(e))}</div></div></div>`}
function render(){if(!state.user)return renderLogin();if(!state.ready)return appEl.innerHTML='<div class="wrap"><div class="card"><h2>Loading...</h2></div></div>';renderApp()}
function nav(v){state.view=v;localStorage.setItem('cvsView',v);render()} window.nav=nav;

function renderLogin(){appEl.innerHTML=`<div class="wrap login"><div><div class="hero brandHero loginBrandHero"><div class="brandLeft"><img src="images/church-logo.svg" class="powerDinkLogo" alt="Church logo"><span class="brandDivider"></span><div class="brandTitle"><h1>Church Volunteer Scheduler</h1><p>View your next service and volunteer assignment.</p></div></div></div><div class="card"><h2>Login</h2><label>Email</label><input id="email" type="email"><label>Password</label><div class="passwordBox"><input id="pass" type="password"><button class="secondary" onclick="togglePass('pass',this)">Show</button></div><div class="row" style="margin-top:14px"><button onclick="login()">Login</button><button class="secondary" onclick="createAccount()">Create Account</button><button class="ghost" onclick="forgotPassword()">Forgot Password</button></div><p class="small">New accounts start as Pending. Pending users can view the next service and calendar while waiting for approval.</p></div></div></div>`}
window.togglePass=(id,b)=>{const e=document.getElementById(id);e.type=e.type==='password'?'text':'password';b.textContent=e.type==='password'?'Show':'Hide'};
window.login=async()=>{try{await signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#pass').value)}catch(e){alert(friendly(e))}};
window.createAccount=async()=>{try{const email=$('#email').value.trim(),pass=$('#pass').value;if(!email||!pass)return alert('Enter email and password.');await createUserWithEmailAndPassword(auth,email,pass)}catch(e){alert(friendly(e))}};
window.forgotPassword=async()=>{const email=$('#email')?.value.trim()||prompt('Enter your email');if(!email)return;try{await sendPasswordResetEmail(auth,email);alert('Password reset email sent.')}catch(e){alert(friendly(e))}};
window.logout=()=>signOut(auth);

function renderApp(){const tabs=[['home','Home'],['calendar','Calendar'],['profile','Profile']];if(isCoordinator())tabs.push(['schedule','Schedule']);if(isAdmin())tabs.push(['admin','Admin']);appEl.innerHTML=`<div class="wrap"><div class="hero heroWithBell brandHero"><div class="brandLeft"><img src="images/church-logo.svg" class="powerDinkLogo" alt="Church logo"><span class="brandDivider"></span><div class="brandTitle"><h1>Church Volunteer Scheduler</h1><p>${esc(state.profile?.name||state.user.email)} • ${esc(roleLabel(state.profile?.role))}</p></div></div></div><div class="tabs">${tabs.map(([v,l])=>`<button class="tab ${state.view===v?'active':''}" onclick="nav('${v}')">${l}</button>`).join('')}<button class="tab" onclick="logout()">Logout</button></div><main id="main"></main><div class="footer">Securely connected • Church Volunteer Scheduler v1.0.0-alpha3</div></div>`;if(state.view==='calendar')renderCalendar();else if(state.view==='profile')renderProfile();else if(state.view==='schedule'&&isCoordinator())renderSchedule();else if(state.view==='admin'&&isAdmin())renderAdmin();else renderHome()}
const roleLabel=r=>({pending:'Pending / Schedule View',scheduleViewer:'Schedule Viewer',volunteer:'Volunteer',coordinator:'Coordinator',admin:'Admin'}[r]||'Pending');
function visibleMinistries(){return state.ministries.filter(m=>m.visible!==false&&!m.archived)}
function visibleRoles(ministryId){return state.roles.filter(r=>r.ministryId===ministryId&&r.visible!==false&&!r.archived)}
function upcomingServices(){return [...state.services].filter(s=>!s.archived&&s.date&&new Date(s.date+'T23:59:59')>=new Date()).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start))}
function serviceAssignments(id){return state.assignments.filter(a=>a.serviceId===id&&!a.archived)}
function myAssignments(){return state.assignments.filter(a=>a.volunteerId===state.user.uid&&!a.archived)}

function renderHome(){const upcoming=upcomingServices();if(isVolunteer())return renderVolunteerHome(upcoming);const next=upcoming[0];$('#main').innerHTML=next?`<div class="sectionTitle"><h2>Next Service</h2><p class="small">Read-only schedule view</p></div>${serviceFeature(next,false)}${upcoming.slice(1).length?`<h2 class="otherTitle">Upcoming Services</h2>${upcoming.slice(1).map(serviceCollapsed).join('')}`:''}`:`<div class="card"><h2>No upcoming services</h2><p class="small">The next service will appear here when a coordinator adds it.</p></div>`}
function renderVolunteerHome(upcoming){const mine=myAssignments().map(a=>({a,s:state.services.find(s=>s.id===a.serviceId)})).filter(x=>x.s&&!x.s.archived&&new Date(x.s.date+'T23:59:59')>=new Date()).sort((x,y)=>(x.s.date+x.s.start).localeCompare(y.s.date+y.s.start));const next=mine[0];$('#main').innerHTML=next?`<div class="sectionTitle"><h2>My Next Assignment</h2><p class="small">Your nearest volunteer schedule</p></div>${assignmentFeature(next.s,next.a)}${mine.slice(1).length?`<h2 class="otherTitle">Upcoming Assignments</h2>${mine.slice(1).map(x=>assignmentCollapsed(x.s,x.a)).join('')}`:''}`:`<div class="card"><h2>No upcoming assignments</h2><p class="small">You can still view the complete church calendar.</p></div>${upcoming[0]?serviceFeature(upcoming[0],false):''}`}
function serviceFeature(s){const as=serviceAssignments(s.id);return `<section class="featuredEvent"><div class="featuredRibbon">⛪ NEXT SERVICE</div><div class="featuredDate"><span>${new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span><b>${new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{month:'short'}).toUpperCase()}</b><strong>${new Date(s.date+'T12:00:00').getDate()}</strong><em>${new Date(s.date+'T12:00:00').getFullYear()}</em></div><div class="featuredMain"><div class="featuredTop"><div><h2>${esc(s.title||'Church Service')}</h2><p>🕒 ${timeLabel(s.start)}${s.end?' - '+timeLabel(s.end):''}<br>📍 ${esc(s.location||'Location TBD')}</p></div><div class="featuredBadges"><span class="badge green">${esc((s.status||'scheduled').toUpperCase())}</span></div></div>${s.notes?`<div class="notice info">${esc(s.notes)}</div>`:''}<h3>Scheduled Volunteers</h3>${renderAssignmentList(as)}</div></section>`}
function assignmentFeature(s,a){const m=state.ministries.find(x=>x.id===a.ministryId);return `<section class="featuredEvent"><div class="featuredRibbon">⭐ MY NEXT ASSIGNMENT</div><div class="featuredDate"><span>${new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span><b>${new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{month:'short'}).toUpperCase()}</b><strong>${new Date(s.date+'T12:00:00').getDate()}</strong><em>${new Date(s.date+'T12:00:00').getFullYear()}</em></div><div class="featuredMain"><h2>${esc(s.title||'Church Service')}</h2><p>🕒 ${timeLabel(s.start)}${s.end?' - '+timeLabel(s.end):''}<br>📍 ${esc(s.location||'Location TBD')}</p><div class="notice"><b>Ministry:</b> ${esc(m?.name||'Ministry')}<br><b>Role:</b> ${esc(a.roleName||'Volunteer')}</div></div></section>`}
function serviceCollapsed(s){return `<details class="eventDetailsCard"><summary><div class="miniDate"><span>${new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span><b>${new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{month:'short'}).toUpperCase()}</b><strong>${new Date(s.date+'T12:00:00').getDate()}</strong></div><div class="miniInfo"><b>${esc(s.title||'Service')}</b><span>${timeLabel(s.start)} • ${esc(s.location||'TBD')}</span></div><div class="miniCount">👥 ${serviceAssignments(s.id).length} assigned</div><button class="secondary expandBtn">Expand</button></summary><div class="eventExpanded">${renderAssignmentList(serviceAssignments(s.id))}</div></details>`}
function assignmentCollapsed(s,a){const m=state.ministries.find(x=>x.id===a.ministryId);return `<details class="eventDetailsCard"><summary><div class="miniDate"><span>${new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{weekday:'short'})}</span><b>${new Date(s.date+'T12:00:00').toLocaleDateString(undefined,{month:'short'}).toUpperCase()}</b><strong>${new Date(s.date+'T12:00:00').getDate()}</strong></div><div class="miniInfo"><b>${esc(s.title||'Service')}</b><span>${esc(m?.name||'Ministry')} • ${esc(a.roleName||'Volunteer')}</span></div><button class="secondary expandBtn">Expand</button></summary><div class="eventExpanded"><p>🕒 ${timeLabel(s.start)} • 📍 ${esc(s.location||'TBD')}</p></div></details>`}
function renderAssignmentList(list){if(!list.length)return '<p class="small">No volunteers assigned yet.</p>';return list.map(a=>{const u=state.users.find(x=>x.id===a.volunteerId);const m=state.ministries.find(x=>x.id===a.ministryId);return `<div class="person"><span><b>${esc(a.volunteerName||u?.name||'Volunteer')}</b><div class="small">${esc(m?.name||'Ministry')} • ${esc(a.roleName||'Volunteer')}</div></span></div>`}).join('')}

function renderCalendar(){const [y,m]=state.calendarMonth.split('-').map(Number),first=new Date(y,m-1,1),days=new Date(y,m,0).getDate(),start=first.getDay(),by={};state.services.filter(s=>!s.archived).forEach(s=>(by[s.date]??=[]).push(s));let cells='';for(let i=0;i<start;i++)cells+='<div class="calendarCell empty"></div>';for(let d=1;d<=days;d++){const date=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;cells+=`<button class="calendarCell ${date===state.selectedCalendarDate?'selected':''} ${date===nowDate()?'today':''}" onclick="selectCalendarDate('${date}')"><span>${d}</span>${by[date]?.length?`<b>${by[date].length} service</b>`:''}</button>`}const selected=by[state.selectedCalendarDate]||[];$('#main').innerHTML=`<div class="card calendarCard"><div class="calendarHeader"><button class="secondary" onclick="changeCalendarMonth(-1)">‹</button><h2>${first.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button class="secondary" onclick="changeCalendarMonth(1)">›</button></div><div class="calendarWeekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<div>${x}</div>`).join('')}</div><div class="calendarGrid">${cells}</div><div class="calendarSelected"><h3>${fmtDate(state.selectedCalendarDate)}</h3>${selected.length?selected.map(s=>`<div class="calendarEvent"><div><b>${esc(s.title||'Service')}</b><div class="small">${timeLabel(s.start)} • ${esc(s.location||'TBD')}</div></div><div>${serviceAssignments(s.id).length} assigned</div></div>`).join(''):'<p class="small">No service scheduled for this date.</p>'}</div></div>`}
window.selectCalendarDate=d=>{state.selectedCalendarDate=d;renderCalendar()};window.changeCalendarMonth=n=>{const [y,m]=state.calendarMonth.split('-').map(Number),d=new Date(y,m-1+n,1);state.calendarMonth=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;state.selectedCalendarDate=state.calendarMonth+'-01';renderCalendar()};

function renderProfile(){const p=state.profile;$('#main').innerHTML=`<div class="card"><h2>Profile</h2><label>Name</label><input id="profileName" value="${esc(p.name||'')}"><label>Email</label><input value="${esc(state.user.email)}" disabled><label>Phone</label><input id="profilePhone" value="${esc(p.phone||'')}"><label>Account Type</label><input value="${esc(roleLabel(p.role))}" disabled><button style="margin-top:12px" onclick="saveProfile()">Save Profile</button></div><div class="card"><h2>Change Password</h2><input id="newPassword" type="password" placeholder="New password"><button style="margin-top:10px" onclick="changeMyPassword()">Change Password</button></div>`}
window.saveProfile=async()=>{await updateDoc(doc(db,'users',state.user.uid),{name:$('#profileName').value.trim(),phone:$('#profilePhone').value.trim()});alert('Profile saved.')};window.changeMyPassword=async()=>{const p=$('#newPassword').value;if(p.length<6)return alert('Use at least 6 characters.');try{await updatePassword(state.user,p);alert('Password changed.')}catch(e){alert(friendly(e))}};

function renderSchedule(){const services=[...state.services].filter(s=>!s.archived).sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start));$('#main').innerHTML=`<div class="card"><h2>Create / Edit Service</h2><input id="serviceId" type="hidden"><label>Service Name</label><input id="serviceTitle" value="Sunday Service"><div class="row"><div><label>Date</label><input id="serviceDate" type="date" value="${nowDate()}"></div><div><label>Start</label><input id="serviceStart" type="time" value="09:00"></div><div><label>End</label><input id="serviceEnd" type="time" value="11:00"></div></div><label>Location</label><input id="serviceLocation" value="Main Sanctuary"><label>Status</label><select id="serviceStatus"><option>scheduled</option><option>ready</option><option>cancelled</option></select><label>Notes</label><textarea id="serviceNotes"></textarea><div class="row"><button onclick="saveService()">Save Service</button><button class="secondary" onclick="clearServiceForm()">Clear</button></div></div><div class="card"><h2>Services</h2>${services.length?services.map(scheduleCard).join(''):'<p class="small">No services yet.</p>'}</div>`}
function scheduleCard(s){return `<details class="coordEventCard"><summary><div><div class="big">${fmtDate(s.date)} — ${esc(s.title||'Service')}</div><p>${timeLabel(s.start)} • ${esc(s.location||'TBD')} • ${serviceAssignments(s.id).length} assigned</p></div><div class="coordSummaryRight"><span class="badge green">${esc((s.status||'scheduled').toUpperCase())}</span><span class="coordExpandText">Expand</span></div></summary><div class="coordEventBody"><div class="row"><button class="secondary" onclick="editService('${s.id}')">Edit</button><button onclick="duplicateService('${s.id}')">Duplicate</button><button class="secondary" onclick="archiveService('${s.id}')">Archive</button>${isAdmin()?`<button class="danger" onclick="deleteService('${s.id}')">Delete</button>`:''}</div><h3>Assignments</h3>${renderEditableAssignments(s)}</div></details>`}
function renderEditableAssignments(s){const list=serviceAssignments(s.id);const mins=visibleMinistries();const firstMin=mins[0]?.id||'';return `${list.map(a=>`<div class="person"><span><b>${esc(a.volunteerName||'Volunteer')}</b><div class="small">${esc(state.ministries.find(m=>m.id===a.ministryId)?.name||'Ministry')} • ${esc(a.roleName||'Volunteer')}</div></span><button class="danger" onclick="removeAssignment('${a.id}')">Remove</button></div>`).join('')||'<p class="small">No assignments yet.</p>'}<div class="row"><select id="vol-${s.id}">${state.users.filter(u=>['volunteer','coordinator','admin'].includes(u.role)).map(u=>`<option value="${u.id}">${esc(u.name||u.email)}</option>`).join('')}</select><select id="min-${s.id}" onchange="refreshRoleOptions('${s.id}')">${mins.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('')}</select><select id="role-${s.id}">${visibleRoles(firstMin).map(r=>`<option value="${esc(r.name)}">${esc(r.name)}</option>`).join('')||'<option value="Volunteer">Volunteer</option>'}</select><button onclick="addAssignment('${s.id}')">Add Volunteer</button></div>`}
window.refreshRoleOptions=sid=>{const mid=$(`#min-${sid}`).value,sel=$(`#role-${sid}`),roles=visibleRoles(mid);sel.innerHTML=roles.length?roles.map(r=>`<option value="${esc(r.name)}">${esc(r.name)}</option>`).join(''):'<option value="Volunteer">Volunteer</option>'};
window.saveService=async()=>{const id=$('#serviceId').value,data={title:$('#serviceTitle').value.trim(),date:$('#serviceDate').value,start:$('#serviceStart').value,end:$('#serviceEnd').value,location:$('#serviceLocation').value.trim(),status:$('#serviceStatus').value,notes:$('#serviceNotes').value.trim(),archived:false,updatedAt:serverTimestamp()};if(!data.title||!data.date||!data.start)return alert('Complete service name, date, and time.');if(id)await updateDoc(doc(db,'services',id),data);else await addDoc(collection(db,'services'),{...data,createdAt:serverTimestamp()});clearServiceForm()};
window.editService=id=>{const s=state.services.find(x=>x.id===id);$('#serviceId').value=id;$('#serviceTitle').value=s.title||'';$('#serviceDate').value=s.date||'';$('#serviceStart').value=s.start||'';$('#serviceEnd').value=s.end||'';$('#serviceLocation').value=s.location||'';$('#serviceStatus').value=s.status||'scheduled';$('#serviceNotes').value=s.notes||'';window.scrollTo({top:0,behavior:'smooth'})};window.clearServiceForm=()=>renderSchedule();
window.duplicateService=async id=>{const s=state.services.find(x=>x.id===id);const newDate=prompt('New service date (YYYY-MM-DD):',s.date);if(!newDate)return;const ref=await addDoc(collection(db,'services'),{title:s.title,date:newDate,start:s.start,end:s.end,location:s.location,status:'scheduled',notes:s.notes||'',archived:false,createdAt:serverTimestamp()});const copy=confirm('Copy volunteer assignments too?');if(copy){for(const a of serviceAssignments(id))await addDoc(collection(db,'assignments'),{serviceId:ref.id,volunteerId:a.volunteerId,volunteerName:a.volunteerName,ministryId:a.ministryId,roleName:a.roleName,createdAt:serverTimestamp()})}alert('Service duplicated.')};
window.archiveService=id=>updateDoc(doc(db,'services',id),{archived:true});window.deleteService=async id=>{if(confirm('Permanently delete this service?'))await deleteDoc(doc(db,'services',id))};
window.addAssignment=async sid=>{const uid=$(`#vol-${sid}`).value,mid=$(`#min-${sid}`).value,roleName=$(`#role-${sid}`).value||'Volunteer',u=state.users.find(x=>x.id===uid);if(!uid||!mid)return alert('Select a volunteer and ministry.');await addDoc(collection(db,'assignments'),{serviceId:sid,volunteerId:uid,volunteerName:u?.name||u?.email||'Volunteer',ministryId:mid,roleName,createdAt:serverTimestamp()})};window.removeAssignment=id=>deleteDoc(doc(db,'assignments',id));

function renderAdmin(){const pending=state.users.filter(u=>u.role==='pending'||u.status==='pending');$('#main').innerHTML=`<div class="dash"><div class="stat"><span>Users</span><b>${state.users.length}</b></div><div class="stat"><span>Pending</span><b>${pending.length}</b></div><div class="stat"><span>Ministries</span><b>${state.ministries.length}</b></div><div class="stat"><span>Services</span><b>${state.services.length}</b></div></div><div class="card"><h2>Pending Accounts</h2>${pending.map(userCard).join('')||'<p class="small">No pending accounts.</p>'}</div><div class="card"><h2>Manage Users</h2>${state.users.map(userCard).join('')}</div><div class="card"><h2>Manage Ministries & Roles</h2>${state.ministries.map(ministryCard).join('')||'<p class="small">No ministries yet.</p>'}<div class="row"><input id="newMinistry" placeholder="New ministry name"><button onclick="addMinistry()">Add Ministry</button></div></div>`}
function userCard(u){return `<div class="person"><div><b>${esc(u.name||u.email)}</b><div class="small">${esc(u.email||'')} • ${esc(roleLabel(u.role))}</div></div><div class="actions"><select id="role-${u.id}"><option value="pending" ${u.role==='pending'?'selected':''}>Pending</option><option value="scheduleViewer" ${u.role==='scheduleViewer'?'selected':''}>Schedule Viewer</option><option value="volunteer" ${u.role==='volunteer'?'selected':''}>Volunteer</option><option value="coordinator" ${u.role==='coordinator'?'selected':''}>Coordinator</option><option value="admin" ${u.role==='admin'?'selected':''}>Admin</option></select><button onclick="saveUserRole('${u.id}')">Save</button></div></div>`}
window.saveUserRole=async id=>{const role=$(`#role-${id}`).value;await updateDoc(doc(db,'users',id),{role,status:role==='pending'?'pending':'active'});alert('User role updated.')};
function ministryCard(m){const roles=state.roles.filter(r=>r.ministryId===m.id);return `<div class="statusBox"><div class="person"><div><b>${esc(m.name)}</b><div class="small">${m.archived?'Archived':(m.visible===false?'Hidden • Active':'Visible • Active')}</div></div><div class="actions"><button class="secondary" onclick="toggleMinistry('${m.id}',${m.visible===false})">${m.visible===false?'Show':'Hide'}</button><button class="secondary" onclick="renameMinistry('${m.id}')">Edit</button><button class="secondary" onclick="archiveMinistry('${m.id}')">Archive</button><button class="danger" onclick="deleteMinistry('${m.id}')">Delete</button></div></div><h3>Roles</h3>${roles.map(roleCard).join('')||'<p class="small">No roles yet.</p>'}<div class="row"><input id="newRole-${m.id}" placeholder="New role name"><button onclick="addRole('${m.id}')">Add Role</button><button class="secondary" onclick="addDefaultTechRoles('${m.id}')">Add Default Tech Roles</button></div></div>`}
function roleCard(r){return `<div class="person"><div><b>${esc(r.name)}</b><div class="small">${r.archived?'Archived':(r.visible===false?'Hidden • Active':'Visible • Active')}</div></div><div class="actions"><button class="secondary" onclick="toggleRole('${r.id}',${r.visible===false})">${r.visible===false?'Show':'Hide'}</button><button class="secondary" onclick="renameRole('${r.id}')">Edit</button><button class="secondary" onclick="archiveRole('${r.id}')">Archive</button><button class="danger" onclick="deleteRole('${r.id}')">Delete</button></div></div>`}
window.addMinistry=async()=>{const name=$('#newMinistry').value.trim();if(!name)return;await addDoc(collection(db,'ministries'),{name,visible:true,archived:false,sortOrder:state.ministries.length+1,createdAt:serverTimestamp()})};window.toggleMinistry=(id,show)=>updateDoc(doc(db,'ministries',id),{visible:show});window.renameMinistry=async id=>{const m=state.ministries.find(x=>x.id===id),name=prompt('Ministry name:',m.name);if(name)await updateDoc(doc(db,'ministries',id),{name})};window.archiveMinistry=id=>updateDoc(doc(db,'ministries',id),{archived:true,visible:false});window.deleteMinistry=async id=>{if(confirm('Permanently delete this ministry?'))await deleteDoc(doc(db,'ministries',id))};

window.addRole=async ministryId=>{const input=$(`#newRole-${ministryId}`),name=input.value.trim();if(!name)return;await addDoc(collection(db,'roles'),{name,ministryId,visible:true,archived:false,sortOrder:state.roles.filter(r=>r.ministryId===ministryId).length+1,createdAt:serverTimestamp()});input.value=''};
window.addDefaultTechRoles=async ministryId=>{const defaults=['ProPresenter','FOH','Lights','FB Sound','Camera Switcher'];const existing=new Set(state.roles.filter(r=>r.ministryId===ministryId).map(r=>String(r.name).toLowerCase()));for(const name of defaults){if(!existing.has(name.toLowerCase()))await addDoc(collection(db,'roles'),{name,ministryId,visible:true,archived:false,sortOrder:state.roles.filter(r=>r.ministryId===ministryId).length+1,createdAt:serverTimestamp()})}alert('Default tech roles added.')};
window.toggleRole=(id,show)=>updateDoc(doc(db,'roles',id),{visible:show});
window.renameRole=async id=>{const r=state.roles.find(x=>x.id===id),name=prompt('Role name:',r?.name||'');if(name)await updateDoc(doc(db,'roles',id),{name})};
window.archiveRole=id=>updateDoc(doc(db,'roles',id),{archived:true,visible:false});
window.deleteRole=async id=>{if(confirm('Permanently delete this role?'))await deleteDoc(doc(db,'roles',id))};
